version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=artgallery
      # - PGDATA=/data/postgres
    volumes:
      - "./data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      # PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - './data:/var/lib/rabbitmq/mnesia'
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    image: 'rabbitmq:3-management'
