version: '3.8'

services:
  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=artgallery
      # - PGDATA=/data/postgres
    volumes:
      - "./pgdata:/var/lib/postgresql/data:rwx"
    ports:
      - "5432:5432"