app:
  props:
    images:
      path: file/src/main/resources/storage/

server:
  port: 8082
  error:
    include-stacktrace: never
    include-message: always
spring:
  application:
    name: file-service
  datasource:
    url: jdbc:postgresql://localhost:5432/files
    username: postgres
    password: 27072001
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
