app:
  props:
    images:
      path: C:\\art-gallery-images
      width: 300
      height: 300

server:
  port: 8082
  error:
    include-stacktrace: never
    include-message: always
spring:
  application:
    name: file-service
  datasource:
    url: jdbc:postgresql://localhost:5432/files
    username: postgres
    password: 27072001
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true