app:
  props:
    images:
      path: file/src/main/resources/storage/
    user:
      system:
        username: file@gmail.com
        password: 11111111

server:
  port: 8082
  error:
    include-stacktrace: never
    include-message: always
spring:
  application:
    name: file-service
  datasource:
    url: jdbc:postgresql://localhost:5432/file
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
