app:
  props:
    account:
      avatar_width: 300
      avatar_height: 300
    facility:
      image_width: 500
      image_height: 500
    images:
      original_width: 1920
      original_height: 1080
      thumbnail_width: 370
      thumbnail_height: 370
      path: file/src/main/resources/storage/
    token:
      secret: my_secret_key
      expired: 86400000
    admin:
      email: admin@gmail.com
      password: admin123
      do-init: true

server:
  port: 8081
  error:
    include-stacktrace: never
    include-message: always
spring:
  mail:
    host: smtp.mail.ru
    port: 465
    username: art.gallery.service@mail.ru
    password: Fzfx5NXRpWse3gcR3u9J
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            trust: smtp.mail.ru
            protocols: TLSv1.2
  application:
    name: art-service
  datasource:
    url: jdbc:postgresql://localhost:5432/art
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
       format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _AUDIT
            revision_field_name: REVISION_ID
            revision_type_field_name: REVISION_TYPE
    open-in-view: false
  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.xml




