app:
  props:
    token:
      secret: my_secret_key
      expired: 86400000
server:
  port: 8081
  error:
    include-stacktrace: never
    include-message: always
spring:
  application:
    name: art-service
  zipkin:
    enabled: true
    service.name: art-service
    sender.type: web
    base-url: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/art
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _AUDIT
            revision_field_name: REVISION_ID
            revision_type_field_name: REVISION_TYPE
  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


