app:
  props:
    images:
      path: /var/art-gallery/attachments/
    token:
      secret: my_secret_key
      expired: 86400000

server:
  port: 8081
  error:
    include-stacktrace: never
    include-message: always
spring:
  application:
    name: art-service
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:5432/art
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _AUDIT
            revision_field_name: REVISION_ID
            revision_type_field_name: REVISION_TYPE
  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.xml


