server:
    port: 8081
spring:
    application:
        name: art-service
    datasource:
        url: jdbc:postgresql://localhost:5432/art
        username: postgres
        password: 994499_ma
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
        
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true


